# Generated by Django 4.2.5 on 2023-09-20 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('contact_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('udg_email', models.EmailField(max_length=254)),
                ('emergency_phone', models.CharField(max_length=15)),
                ('url_socialnet', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='School_Cycle',
            fields=[
                ('cycle_id', models.AutoField(primary_key=True, serialize=False)),
                ('period', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=9, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=10)),
                ('contact_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='studentform.contact')),
            ],
        ),
    ]
