# Generated by Django 4.2.5 on 2023-10-06 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_id',
            new_name='idContact',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='student_id',
            new_name='idStudent',
        ),
        migrations.RenameField(
            model_name='school_cycle',
            old_name='cycle_id',
            new_name='idCycle',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='idStudent',
        ),
        migrations.AddField(
            model_name='student',
            name='admission_cycle',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
