# Generated by Django 4.2.5 on 2023-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0002_rename_contact_id_contact_idcontact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='emergency_phone',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=25),
        ),
    ]
