# Generated by Django 4.2.5 on 2023-10-31 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0004_contact_company_contact_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='school_cycle',
            name='period',
        ),
        migrations.AddField(
            model_name='school_cycle',
            name='cycle_period',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='school_cycle',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school_cycle',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='school_cycle',
            name='year',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
