# Generated by Django 4.2.5 on 2023-11-01 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0007_career_status_student_first_last_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='admission_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='admission_cycle', to='studentform.school_cycle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='first_last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='idCareer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='studentform.career'),
        ),
        migrations.AlterField(
            model_name='student',
            name='last_cycle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='last_cycle', to='studentform.school_cycle'),
        ),
        migrations.AlterField(
            model_name='student',
            name='second_last_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='studentform.status'),
        ),
    ]
