# Generated by Django 4.2.5 on 2023-12-01 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0008_alter_student_admission_cycle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='exchange',
            field=models.BooleanField(default=False),
        ),
    ]
