# Generated by Django 4.2.5 on 2023-12-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0010_remove_career_needed_credits_remove_career_semesters_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('key_subject', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=80)),
                ('credits', models.PositiveSmallIntegerField()),
                ('has_extraordinary', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='semester',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studentform.subject'),
        ),
    ]
