# Generated by Django 4.2.5 on 2023-11-21 14:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('studentform', '0008_alter_student_admission_cycle_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GradePeriod',
            fields=[
                ('idGradePeriod', models.AutoField(primary_key=True, serialize=False)),
                ('code_name', models.CharField(max_length=3)),
                ('grade_period', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('idSubject', models.AutoField(primary_key=True, serialize=False)),
                ('key_subject', models.CharField(max_length=7)),
                ('name', models.CharField(max_length=50)),
                ('credits', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('idSection', models.AutoField(primary_key=True, serialize=False)),
                ('nrc', models.CharField(max_length=15)),
                ('section', models.CharField(max_length=5)),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studenthistory.subject')),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('idCourse', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.PositiveSmallIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('grade_period', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studenthistory.gradeperiod')),
                ('school_cycle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentform.school_cycle')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studenthistory.section')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentform.student')),
            ],
        ),
        migrations.CreateModel(
            name='CareerSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentform.career')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studenthistory.subject')),
            ],
            options={
                'unique_together': {('career', 'subject')},
            },
        ),
    ]
