# Generated by Django 4.2.5 on 2023-11-27 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthistory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='has_extraordinary',
            field=models.BooleanField(default=True),
        ),
    ]
