# Generated by Django 4.2.5 on 2023-11-27 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studenthistory', '0002_subject_has_extraordinary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=80),
        ),
    ]
