# Generated by Django 4.2.5 on 2023-12-19 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0010_remove_career_needed_credits_remove_career_semesters_and_more'),
        ('studenthistory', '0004_alter_course_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='semester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='studentform.semester'),
        ),
    ]
