# Generated by Django 4.2.5 on 2023-12-19 23:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentform', '0011_subject_semester_subject'),
        ('studenthistory', '0005_subject_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='careersubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studentform.subject'),
        ),
        migrations.AlterField(
            model_name='section',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='studentform.subject'),
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
